<img src="idal-logo.png" align="right" style="float" width="400">
<font color="#CA3532"><h1 align="left">mIA3</h1></font>
<font color="#6E6E6E"><h2 align="left">Tarea 11. Numpy.</h2></font> 

#### Juan Gómez-Sanchis

In [2]:
import numpy as np
array8_1=np.arange(20,31,1)
array8_1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [4]:
array8_2=array8_1[:6]
# Lo mismo 
array8_2=array8_1[0:6]
array8_2


array([20, 21, 22, 23, 24, 25])

In [21]:
Ejer3a=np.arange(100,201,1)
Ejer3b=Ejer3a[:10]
Ejer3b

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [22]:
Ejer3b[::2]=9999
Ejer3b

array([9999,  101, 9999,  103, 9999,  105, 9999,  107, 9999,  109])

In [5]:
Ejer5a=np.arange(9,0,-1)

Ejer5a=Ejer5a.reshape(3,3) #Por defecto es por filas, style
#Ejer5a=Ejer5a.reshape(3,3, order='C') #C style (por filas, cambia el ultimo índice)
#Ejer5a=Ejer5a.reshape(3,3, order='F') #Fortran style (por columna, cambia el primer índice)
print(Ejer5a)


Ejer5b=Ejer5a[:2,:]
print(Ejer5b)

Ejer5c=Ejer5a[:,:2]
print(Ejer5c)

Ejer5d=Ejer5a[1:,:2]
Ejer5d

[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7]
 [6 5 4]]
[[9 8]
 [6 5]
 [3 2]]


array([[6, 5],
       [3, 2]])