<img src="idal-logo.png" align="right" style="float" width="400">
<font color="#CA3532"><h1 align="left">mIA3</h1></font>
<font color="#6E6E6E"><h2 align="left">Tarea 12. Numpy.</h2></font> 

#### Juan Gómez-Sanchis

In [1]:
import numpy as np

Ejer1=np.arange(1,21,1).reshape(2,10)
Ejer1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [2]:
Ejer2=np.ones((2,10))*10
Ejer2
np.dot(Ejer2,Ejer1.T)

array([[ 550., 1550.],
       [ 550., 1550.]])

In [3]:
Ejer3=np.arange(1,451,1).reshape(10,9,5)
Ejer3

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45]],

       [[ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90]],

       [[ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100],
        [101, 102, 103, 104, 105],
        [106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115],
        [116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135]],

       [[136, 137, 138, 139, 140],
        [141, 

In [4]:
Ejer4a=Ejer3[0,:,:]
Ejer4a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [5]:
Ejer4b=Ejer3[9,:,:]
Ejer4b

array([[406, 407, 408, 409, 410],
       [411, 412, 413, 414, 415],
       [416, 417, 418, 419, 420],
       [421, 422, 423, 424, 425],
       [426, 427, 428, 429, 430],
       [431, 432, 433, 434, 435],
       [436, 437, 438, 439, 440],
       [441, 442, 443, 444, 445],
       [446, 447, 448, 449, 450]])

In [6]:
np.dot(Ejer4a,Ejer4b.T)

array([[ 6130,  6205,  6280,  6355,  6430,  6505,  6580,  6655,  6730],
       [16330, 16530, 16730, 16930, 17130, 17330, 17530, 17730, 17930],
       [26530, 26855, 27180, 27505, 27830, 28155, 28480, 28805, 29130],
       [36730, 37180, 37630, 38080, 38530, 38980, 39430, 39880, 40330],
       [46930, 47505, 48080, 48655, 49230, 49805, 50380, 50955, 51530],
       [57130, 57830, 58530, 59230, 59930, 60630, 61330, 62030, 62730],
       [67330, 68155, 68980, 69805, 70630, 71455, 72280, 73105, 73930],
       [77530, 78480, 79430, 80380, 81330, 82280, 83230, 84180, 85130],
       [87730, 88805, 89880, 90955, 92030, 93105, 94180, 95255, 96330]])

In [7]:
Ejer4c=Ejer3[1,1,:]
Ejer4c

array([51, 52, 53, 54, 55])

In [8]:
Ejer4d=Ejer3[2,0,:]
Ejer4d

array([91, 92, 93, 94, 95])

In [9]:
np.dot(Ejer4c,Ejer4d)

24655

In [10]:
Ejer4e=Ejer3[0,:,4]
Ejer4e

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [11]:
Ejer4f=Ejer3[3,:,2]
Ejer4f

array([138, 143, 148, 153, 158, 163, 168, 173, 178])

In [12]:
np.dot(Ejer4e,Ejer4f)

37050