<img src="idal-logo.png" align="right" style="float" width="400">
<font color="#CA3532"><h1 align="left">mIA3</h1></font>
<font color="#6E6E6E"><h2 align="left">Tarea 10. Numpy.</h2></font> 

#### Juan Gómez-Sanchis

In [51]:
import numpy as np
primer_array=np.array([10,12,14,16])
primer_array

array([10, 12, 14, 16])

In [2]:
primer_array.dtype

dtype('int64')

In [3]:
primer_array.shape

(4,)

In [54]:
unos=np.ones((5,4))
print(unos)

ceros=np.zeros(shape=(5,4))
print(ceros)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
identidad=np.eye(7)
identidad

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [6]:
array1a100=np.arange(100)+1
array1a100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [57]:
array2a20=np.arange(2,20,2) #inicio, final, y step
print(array2a20)
array2a20=array2a20.reshape(3,3)

print(array2a20)
array_imp_diagonal=array2a20+np.eye(3)
array_imp_diagonal

[ 2  4  6  8 10 12 14 16 18]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


array([[ 3.,  4.,  6.],
       [ 8., 11., 12.],
       [14., 16., 19.]])

In [8]:
1/array_imp_diagonal

array([[0.33333333, 0.25      , 0.16666667],
       [0.125     , 0.09090909, 0.08333333],
       [0.07142857, 0.0625    , 0.05263158]])

In [9]:
(1/array_imp_diagonal)**0.5

array([[0.57735027, 0.5       , 0.40824829],
       [0.35355339, 0.30151134, 0.28867513],
       [0.26726124, 0.25      , 0.22941573]])

In [40]:
%qtconsole