<img src="idal-logo.png" align="right" style="float" width="400">
<font color="#CA3532"><h1 align="left">mIA3</h1></font>
<font color="#6E6E6E"><h2 align="left">Tarea Evaluable. Python.</h2></font> 

#### Jorge Vila Tomás

**Ejercicio 1. (2 puntos)** La criba de Eratóstenes es un método ideado por Eratóstenes, para conseguir los números primos entre el 1 y un determinado número entero n. Este ejercicio permite poner en práctica muchas de las sentencias de control que hemos visto.


La criba de Eratostenes se puede programar como un algoritmo que consiste en formar  una tabla con todos los números naturales comprendidos entre 2 y n,  se van tachando los números que no son primos de la siguiente manera: 

* Comenzando por el 2 (considerado primo), se tachan todos sus múltiplos.
* Comenzando de nuevo, cuando se encuentra un número entero que no ha sido tachado, ese número es declarado primo, y se procede a tachar todos sus múltiplos.
* El proceso se repite iterativamente. El proceso termina cuando el cuadrado del siguiente número confirmado como primo es mayor que n.

Con todo esto, 

* Crea una función denominada `Eratostenes(n)`, que devuelva los número primos inferiores o iguales a n. 

* El tipo computacional de n es entero, modifica la función anterior `Eratostenes_Err` y crea un nueva función  para que si se introduce un valor real como argumento de la función, no devuelva error y  muestre un mensaje por pantalla informando al usuario de que el argumento sea entero.

### Solución 1

In [1]:
def Eratostenes(n):
    candidates = list(range(2,n+1))
    primos = [1, 2]

    for candidate in candidates: #Con esto quitamos los candidatos múltiplos de 2
        if (candidate % 2 == 0):
            candidates.remove(candidate)

    while primos[-1] ** 2 < n:
        if candidates[0] not in primos:
            primos.append(candidates[0])
        
        for candidate in candidates:
            if candidate % primos[-1] == 0:
                candidates.remove(candidate)

    return primos + candidates #El signo +  es equivalente a usar list.extend() pero es ligeramente más eficiente.

primos = Eratostenes(50)
print(f"Primos: {primos}")

Primos: [1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


Podemos mejorar un poco la implementación del algoritmo si consideramos que, ya que los números pares se van a quitar siempre, podemos generar la lista de candidatos de forma que contenga únicamente los números impares. También añadimos *type hinting* para decirle a la función que el input debe ser, en este caso, de tipo ```int```. Si introducimos cualquier otro tipo de dato la función dará un error. Esto es práctico, como vemos en la Solución 2, porque nos permite utilizar las sentencias ```try/except``` para asegurar un buen uso de nuestra función.

### Solución 1 v2

In [13]:
def Eratostenes(n: int):
    candidates = list(range(3,n+1,2)) #Así te ahorras quitar los pares
    primos = [1, 2]

    while primos[-1] ** 2 < n:
        if candidates[0] not in primos:
            primos.append(candidates[0])
        
        for candidate in candidates:
            if candidate % primos[-1] == 0:
                candidates.remove(candidate)

    return primos + candidates

primos = Eratostenes(50)
print(f"Primos: {primos}")

Primos: [1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


### Solución 2

In [2]:
def Eratostenes_Err(n):
    try:
        primos = Eratostenes(n)
    except:
        print(f"El argumento de la función tiene que ser un número entero pero es de tipo {type(n)}.")
    else:
        return primos

Eratostenes_Err(50)
Eratostenes_Err(50.3)

El argumento de la función tiene que ser un número entero pero es de tipo <class 'float'>.


Como podemos ver, al introducir un valor que no es de tipo ```ìnt``` la función no da error, sino que devuelve un mensaje y nos recuerda que hemos de introducir un número entero. También podríamos haber utilizado una sentencia ```if isinstane(n,float)``` para filtrar únicamente los ```float``` (como pedía el enunciado), pero al hacerlo de esta forma se generaliza más el resultado.

**Ejercicio 2. (1 punto)** Crea una array 8x3 con los enteros entre 10 y 34 de uno en uno. Después crea 4 nuevos arrays 2x3 partiendo el array original de dos en dos filas. 

In [15]:
import numpy as np

In [16]:
#Solución
a = np.arange(10, 34).reshape((8,3)) #Arange nos permite crear un np.array con los valores que buscamos
b = a.flatten()[:6].reshape((2,3)) #Para coger más fácilmente los subarrays utilizamos el método .flatten() y luego les damos la forma deseada
c = a.flatten()[6:12].reshape((2,3))
d = a.flatten()[12:18].reshape((2,3))
e = a.flatten()[18:24].reshape((2,3))
print(f"Array:\n{a} --> Shape: {a.shape}")
print(f"Array:\n{b} --> Shape: {b.shape}")
print(f"Array:\n{c} --> Shape: {c.shape}")
print(f"Array:\n{d} --> Shape: {d.shape}")
print(f"Array:\n{e} --> Shape: {e.shape}")

Array:
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]] --&gt; Shape: (8, 3)
Array:
[[10 11 12]
 [13 14 15]] --&gt; Shape: (2, 3)
Array:
[[16 17 18]
 [19 20 21]] --&gt; Shape: (2, 3)
Array:
[[22 23 24]
 [25 26 27]] --&gt; Shape: (2, 3)
Array:
[[28 29 30]
 [31 32 33]] --&gt; Shape: (2, 3)


**Ejercicio 3. (1 punto)** Crea el siguiente array de numpy:


[[34,43,73],[82,22,12],[53,94,66]]

Calcula:

* El máximo por filas
* El mínimo por columnas 
* La media por columnas
* La desviación típica por filas


### Solución

In [17]:
a = np.array([[34,43,73],[82,22,12],[53,94,66]])
max_a = np.max(a, axis = 1) #axis = 0 corresponde a hacerlo por filas
min_a = np.min(a, axis = 0) #y axis = 1 corresponde a hacerlo por columnas.
mean_a = np.mean(a, axis = 0)
std_a = np.std(a, axis = 1)

print(f"Array original:\n{a}")
print(f"Máximo por filas: {max_a}")
print(f"Mínimo por columnas: {min_a}")
print(f"Media por columnas: {mean_a}")
print(f"Desviación típica por filas: {std_a}")

Array original:
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Máximo por filas: [73 82 94]
Mínimo por columnas: [34 22 12]
Media por columnas: [56.33333333 53.         50.33333333]
Desviación típica por filas: [16.673332   30.91206165 17.10750323]


**Ejercicio 4. (2 puntos)** Carga el dataset `Coches_dataset_jgx_I.csv` empleando la librería `pandas` y sus funciones de importación.

* Una vez cargado, visualiza las 5 primeras muestras del data frame.
* Averigua el número de muestras del data frame.
* Averigua el número de variables.
* Crea una diccionario cuyas claves contengan las posición de la columna y el valor los nombres de las variables del dataframe.


In [18]:
import pandas as pd

In [19]:
#Carga del dataset / Comprobamos que todos los elementos se separan por punto y coma en lugar de comas y la primera fila tiene el nombre de las columnas
coches = pd.read_csv("Coches_dataset_jgx_I.csv", sep = ";")

###  Solución 1
El método ```.head()``` permite visualizar, por defecto, las 5 primeras muestras del dataframe. Si quisieramos visualizar otra cantidad N de muestras tendríamos que utilizar ```.head(N)```.

In [20]:
coches.head()

index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage  price  
0             four         111               21  13495  
1             four         111               21  16500  
2              six         154               19  16500  
3             four         102               24  13950  
4             five         115               18  17450

### Solución 2
Para averiguar el número de muestras del dataframe tenemos varias posibilidades:
- Podemos hacer ```len(coches)```.
- Podemos hacer ```len(coches["CualquierColumna"])```.
- Podemos hacer ```.describe()``` y observar la fila *count*.
- Y podemos hacer ```coches.info()``` y fijarnos en *RangeIndex: N entries*.

In [21]:
len(coches)

61

In [22]:
len(coches["company"])

61

In [23]:
coches.describe()

index  wheel-base      length  horsepower  average-mileage
count  61.000000   61.000000   61.000000   61.000000        61.000000
mean   40.885246   98.481967  173.098361  107.852459        25.803279
std    25.429706    6.679234   14.021846   53.524398         8.129821
min     0.000000   88.400000  141.100000   48.000000        13.000000
25%    18.000000   94.500000  159.100000   68.000000        19.000000
50%    39.000000   96.300000  171.200000  100.000000        25.000000
75%    61.000000  101.200000  177.300000  123.000000        31.000000
max    88.000000  120.900000  208.100000  288.000000        47.000000

In [24]:
coches.info()

&lt;class &#39;pandas.core.frame.DataFrame&#39;&gt;
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   index             61 non-null     int64  
 1   company           61 non-null     object 
 2   body-style        61 non-null     object 
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object 
 6   num-of-cylinders  61 non-null     object 
 7   horsepower        61 non-null     int64  
 8   average-mileage   61 non-null     int64  
 9   price             58 non-null     object 
dtypes: float64(2), int64(3), object(5)
memory usage: 4.9+ KB


###  Solución 3
En un DataFrame, el número de variables corresponde a la cantidad de columnas y también podemos verlas de distintas formas:
- ```len(coches.columns)``` nos permite acceder a las columnas del DataFrame y contarlas.
- ```coches.info()``` también proporciona el número de columnas en *Data columns (total 10 columns)*.

In [25]:
len(coches.columns)

10

In [26]:
coches.info()

&lt;class &#39;pandas.core.frame.DataFrame&#39;&gt;
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   index             61 non-null     int64  
 1   company           61 non-null     object 
 2   body-style        61 non-null     object 
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object 
 6   num-of-cylinders  61 non-null     object 
 7   horsepower        61 non-null     int64  
 8   average-mileage   61 non-null     int64  
 9   price             58 non-null     object 
dtypes: float64(2), int64(3), object(5)
memory usage: 4.9+ KB


### Solucion 4
Crea una diccionario cuyas claves contengan las posición de la columna y el valor los nombres de las variables del dataframe.
Utilizando el primer atributo que comentábamos antes (```.columns```), accedemos a los nombres de las columnas del DataFrame y creamos el diccionario:

In [27]:
dic_coches = {key:value for key, value in enumerate(coches.columns)}
dic_coches

{0: &#39;index&#39;,
 1: &#39;company&#39;,
 2: &#39;body-style&#39;,
 3: &#39;wheel-base&#39;,
 4: &#39;length&#39;,
 5: &#39;engine-type&#39;,
 6: &#39;num-of-cylinders&#39;,
 7: &#39;horsepower&#39;,
 8: &#39;average-mileage&#39;,
 9: &#39;price&#39;}

**Ejercicio 5. (2 puntos)** Limpieza de un dataframe.

* En el data frame existen datos ausentes codificados con símbolos `"?"` y `"n.a"`, reemplaza estos valores por `NaN`. Puedes tirar de sentencias de control, pero si eres hábil puedes utilizar una opción del  método `read_csv` para que en la carga del fichero se lleve a cabo lo que te pido. Almacena el resultado un data frame denominado `df_clean`.

* Elimina la columna `index` del dataframe.
* Elimina aquellas muestras que contengan algún NaN.
* Almacena el data frame `df_clean` en el fichero  `Coches_dataset_jgx_I_clean.csv`empleando como delimitador de datos `;` y sin almacenar el índice de la muestra.

### Solución 1

In [28]:
df_clean = pd.read_csv("Coches_dataset_jgx_I.csv", sep = ";", na_values = ["?", "n.a"])
df_clean.head()

index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

### Solución 2

In [29]:
df_clean.drop(labels = "index", axis = "columns", inplace = True) 
df_clean.head()

company   body-style  wheel-base  length engine-type num-of-cylinders  \
0  alfa-romero  convertible        88.6   168.8        dohc             four   
1  alfa-romero  convertible        88.6   168.8        dohc             four   
2  alfa-romero    hatchback        94.5   171.2        ohcv              six   
3         audi        sedan        99.8   176.6         ohc             four   
4         audi        sedan        99.4   176.6         ohc             five   

   horsepower  average-mileage    price  
0         111               21  13495.0  
1         111               21  16500.0  
2         154               19  16500.0  
3         102               24  13950.0  
4         115               18  17450.0

### Solución 3

In [30]:
print(f"El DataFrame tiene {len(df_clean)} columnas antes de quitar los NaN.")
df_clean.dropna(inplace = True)
print(f"El DataFrame tiene {len(df_clean)} columnas después de quitar los NaN.")

El DataFrame tiene 61 columnas antes de quitar los NaN.
El DataFrame tiene 53 columnas después de quitar los NaN.


### Solución 4

In [31]:
df_clean.to_csv("Coches_dataset_jgx_I_clean.csv", sep = ";", index = False)

**Ejercicio 6. (2 puntos)** Manipulando y extrayendo información del data frame.

* Carga el dataset `Coches_dataset_jgx_I_clean.csv` que has almacenado en el ejercicio anterior. 
* Programa un segmento de código que te permita conocer que marca tiene el coche más caro y su precio.
* Programa un segmento de código que te permita acceder a las muestras correspondientes a los coches `toyota`
* Averigua el número de coches de cada marca hay en el dataset.
* Averigua cual es el coche más caro de cada  marca, su estilo (`'body-style'`), la potencia (`'horsepower'`) y el precio ('price').
* Ordena las muestras del data frame por por precio (`'price'`) y potencia (`'horsepower'`)
* Calcula los principales estadísticos (mean, std, min, max, percetiles 25%, 50%, 75% y el número de muestras diferentes de NaN) de las variables numéricas del dataframe. 

###  Solución 1

In [32]:
coches_clean = pd.read_csv("Coches_dataset_jgx_I_clean.csv", sep = ";")
coches_clean.head()

company   body-style  wheel-base  length engine-type num-of-cylinders  \
0  alfa-romero  convertible        88.6   168.8        dohc             four   
1  alfa-romero  convertible        88.6   168.8        dohc             four   
2  alfa-romero    hatchback        94.5   171.2        ohcv              six   
3         audi        sedan        99.8   176.6         ohc             four   
4         audi        sedan        99.4   176.6         ohc             five   

   horsepower  average-mileage    price  
0         111               21  13495.0  
1         111               21  16500.0  
2         154               19  16500.0  
3         102               24  13950.0  
4         115               18  17450.0

###  Solución 2 

In [33]:
coches_precio = coches_clean.sort_values("price", ascending = False)
coches_precio.head()

company   body-style  wheel-base  length engine-type  \
32  mercedes-benz      hardtop       112.0   199.2        ohcv   
11            bmw        sedan       103.5   193.8         ohc   
31  mercedes-benz        sedan       120.9   208.1        ohcv   
42        porsche  convertible        89.5   168.9        ohcf   
12            bmw        sedan       110.0   197.0         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
32            eight         184               14  45400.0  
11              six         182               16  41315.0  
31            eight         184               14  40960.0  
42              six         207               17  37028.0  
12              six         182               15  36880.0

Vemos que el coche más caro pertenece a la marca Mercedes-Benz y tiene un precio de 45400€.

### Solución 3

In [34]:
toyota = coches_clean[coches_clean["company"] == "toyota"]
toyota.head()

company body-style  wheel-base  length engine-type num-of-cylinders  \
43  toyota  hatchback        95.7   158.7         ohc             four   
44  toyota  hatchback        95.7   158.7         ohc             four   
45  toyota  hatchback        95.7   158.7         ohc             four   
46  toyota      wagon        95.7   169.7         ohc             four   
47  toyota      wagon        95.7   169.7         ohc             four   

    horsepower  average-mileage   price  
43          62               35  5348.0  
44          62               31  6338.0  
45          62               31  6488.0  
46          62               31  6918.0  
47          62               27  7898.0

###  Solución 4
La funcioón ```crosstab``` nos permite crear un DataFrame que "cruce" las características que queramos. Sería equivalente a crear una tabla de contingencia. Al utilizar el argumento *count* simplemente nos cuenta las muestras que corresponden a cada compañia.

In [35]:
coches_marca = pd.crosstab(coches_clean["company"], "count")
coches_marca.head()

col_0        count
company           
alfa-romero      3
audi             4
bmw              6
chevrolet        3
dodge            2

###  Solución 5 
Como ya hemos ordenado antes el DataFrame en función del precio, podemos utilizar el método ```.drop_duplicates``` para eliminar todas las entradas que tienen la misma compañia y así nos quedamos con un DataFrame ordenado por precio que solamente nos muestra el coche más caro de cada marca junto al resto de atributos. Si queremos ver únicamente el estilo, la potencia y el precio también podemos hacerlo seleccionando estas columnas del nuevo DataFrame.

In [36]:
coches_precio_top = coches_precio.drop_duplicates(subset = ["company"])
coches_precio_top

company   body-style  wheel-base  length engine-type  \
32  mercedes-benz      hardtop       112.0   199.2        ohcv   
11            bmw        sedan       103.5   193.8         ohc   
42        porsche  convertible        89.5   168.9        ohcf   
24         jaguar        sedan       102.0   191.7        ohcv   
6            audi        wagon       105.8   192.7         ohc   
29          mazda        sedan       104.9   175.0         ohc   
2     alfa-romero    hatchback        94.5   171.2        ohcv   
48         toyota        wagon       104.5   187.8        dohc   
40         nissan        sedan       100.4   184.6        ohcv   
19          honda        sedan        96.5   175.4         ohc   
52     volkswagen        sedan        97.3   171.7         ohc   
36     mitsubishi        sedan        96.3   172.4         ohc   
21          isuzu        sedan        94.3   170.7         ohc   
15      chevrolet        sedan        94.5   158.8         ohc   
16          dodge    hatchback        93.7   157.3         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
32            eight         184               14  45400.0  
11              six         182               16  41315.0  
42              six         207               17  37028.0  
24           twelve         262               13  36000.0  
6              five         110               19  18920.0  
29             four          72               31  18344.0  
2               six         154               19  16500.0  
48              six         156               19  15750.0  
40              six         152               19  13499.0  
19             four         101               24  12945.0  
52             four         100               26   9995.0  
36             four          88               25   8189.0  
21             four          78               24   6785.0  
15             four          70               38   6575.0  
16             four          68               31   6377.0

In [37]:
coches_precio_top[["company", "body-style", "horsepower", "price"]]

company   body-style  horsepower    price
32  mercedes-benz      hardtop         184  45400.0
11            bmw        sedan         182  41315.0
42        porsche  convertible         207  37028.0
24         jaguar        sedan         262  36000.0
6            audi        wagon         110  18920.0
29          mazda        sedan          72  18344.0
2     alfa-romero    hatchback         154  16500.0
48         toyota        wagon         156  15750.0
40         nissan        sedan         152  13499.0
19          honda        sedan         101  12945.0
52     volkswagen        sedan         100   9995.0
36     mitsubishi        sedan          88   8189.0
21          isuzu        sedan          78   6785.0
15      chevrolet        sedan          70   6575.0
16          dodge    hatchback          68   6377.0

###  Solución 6
Utilizando de nuevo el método ```.sort_values``` podemos ordenar el DataFrame por precio y HorsePower.
Al introducir más de una columna para realizar la ordenación, primero se fija en la primera columna y utiliza las siguientes cuándo se encuentra duplicados.

In [38]:
coches_clean.sort_values(["price", "horsepower"], ascending = False).head()

company   body-style  wheel-base  length engine-type  \
32  mercedes-benz      hardtop       112.0   199.2        ohcv   
11            bmw        sedan       103.5   193.8         ohc   
31  mercedes-benz        sedan       120.9   208.1        ohcv   
42        porsche  convertible        89.5   168.9        ohcf   
12            bmw        sedan       110.0   197.0         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
32            eight         184               14  45400.0  
11              six         182               16  41315.0  
31            eight         184               14  40960.0  
42              six         207               17  37028.0  
12              six         182               15  36880.0

###  Solución 7 

Para calcular los principales estadísticos de un DataFrame podemos utilizar el método ```.describe()```:

In [39]:
coches_clean.describe()

wheel-base      length  horsepower  average-mileage         price
count   53.000000   53.000000   53.000000        53.000000     53.000000
mean    98.324528  172.888679  106.962264        25.566038  15554.943396
std      6.821541   14.119090   50.500176         8.238067  11669.705287
min     88.400000  141.100000   48.000000        13.000000   5151.000000
25%     94.500000  159.100000   68.000000        19.000000   6785.000000
50%     96.300000  171.200000  100.000000        25.000000  10345.000000
75%    101.200000  176.800000  123.000000        31.000000  18344.000000
max    120.900000  208.100000  262.000000        47.000000  45400.000000