## Tarea 4. Importación de funciones y Operadores Binarios

Empezamos importando la librería ``Numpy`` para poder utilizar todas las funciones del módulo. Lo importamos con un alias para simplificar la utilización. También se podrían importar todas las funciones por separado escribiendo ``from numpy import *``

In [1]:
import numpy as np

Podemos crear un numpy array que contenga 5 unos empleando la función ``ones``.

In [3]:
array_1 = np.ones(5)
print(array_1)

[1. 1. 1. 1. 1.]


Si quisieramos emplear únicamente la función ``ones`` del módulo ``numpy`` podríamos importarla por serparada como ``from numpy import ones``

In [4]:
from numpy import ones

In [5]:
array_1_2 = ones(5)
print(array_1_2)

[1. 1. 1. 1. 1.]


Al igual que hemos importado el módulo ``numpy`` con un alias, podemos importar las funciones separadas con un alias también.

In [6]:
from numpy import ones as unos

In [7]:
array_1_3 = unos(5)
print(array_1_3)

[1. 1. 1. 1. 1.]


In [2]:
a = 'Master'
b = "Ciencia"
c = "Datos"
d = 2
h = 4
i = 3
f = 0.5
g = '0.5'

- h^f no está permitida porque no son ``bool``.
- i/d sí está permitida porque los dos son ``int``.
- f+g no está permitido porque no se pueden sumar un ``int`` y un ``str``.
- a+b+c sí está pertmitido porque al sumar ``str`` lo que hacemos es concatenarlas.
- a-d no está permitido porque no se pueden restar un ``str`` y un ``int``.

La variable ``a`` hace referencia a un objeto inmutable porque es un ``str`` y las ``str`` son objetos inmutables.

La función ``is`` lo que hace es comprobar si dos variables apuntan a la misma posición de memoria, mientras que el operador ``==`` comprueba si el valor de las variables es exactamente el mismo.
Es importante conocer la diferencia porque se puede dar el caso en que tengamos dos variables con mismo valor pero que apunten a posiciones de memoria diferentes o viceversa.
Hay que notar que los ``int`` entre [[-5, 256]] se almacenan en la misma posición de memoria.