In [2]:
import numpy as np

## Ejercicio 1

In [4]:
Ejer1 = np.arange(0, 20).reshape((2,10))
print(Ejer1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


## Ejercicio 2

In [5]:
Ejer2 = np.ones((2,10)) * 10
print(Ejer2)

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


In [6]:
np.dot(Ejer1, np.transpose(Ejer2))

array([[ 450.,  450.],
       [1450., 1450.]])

## Ejercicio 3

In [14]:
Ejer3 = np.arange(1,451).reshape((10,9,5))
print(Ejer3)
print(Ejer3.shape)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]
  [ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]]

 [[ 46  47  48  49  50]
  [ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]
  [ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]]

 [[ 91  92  93  94  95]
  [ 96  97  98  99 100]
  [101 102 103 104 105]
  [106 107 108 109 110]
  [111 112 113 114 115]
  [116 117 118 119 120]
  [121 122 123 124 125]
  [126 127 128 129 130]
  [131 132 133 134 135]]

 [[136 137 138 139 140]
  [141 142 143 144 145]
  [146 147 148 149 150]
  [151 152 153 154 155]
  [156 157 158 159 160]
  [161 162 163 164 165]
  [166 167 168 169 170]
  [171 172 173 174 175]
  [176 177 178 179 180]]

 [[181 182 183 184 185]
  [186 187 188 189 190]
  [191 192 193 194 195]
  [196 197 198 199 200]
  [201 202 203 204 205]
  [206 2

## Ejercicio 4

In [16]:
Ejer4a = Ejer3[0,:,:]
print(Ejer4a)
Ejer4b = Ejer3[-1,:,:]
print(Ejer4b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]]
[[406 407 408 409 410]
 [411 412 413 414 415]
 [416 417 418 419 420]
 [421 422 423 424 425]
 [426 427 428 429 430]
 [431 432 433 434 435]
 [436 437 438 439 440]
 [441 442 443 444 445]
 [446 447 448 449 450]]


In [17]:
np.dot(Ejer4a,np.transpose(Ejer4b))

array([[ 6130,  6205,  6280,  6355,  6430,  6505,  6580,  6655,  6730],
       [16330, 16530, 16730, 16930, 17130, 17330, 17530, 17730, 17930],
       [26530, 26855, 27180, 27505, 27830, 28155, 28480, 28805, 29130],
       [36730, 37180, 37630, 38080, 38530, 38980, 39430, 39880, 40330],
       [46930, 47505, 48080, 48655, 49230, 49805, 50380, 50955, 51530],
       [57130, 57830, 58530, 59230, 59930, 60630, 61330, 62030, 62730],
       [67330, 68155, 68980, 69805, 70630, 71455, 72280, 73105, 73930],
       [77530, 78480, 79430, 80380, 81330, 82280, 83230, 84180, 85130],
       [87730, 88805, 89880, 90955, 92030, 93105, 94180, 95255, 96330]])

In [19]:
Ejer4c = Ejer3[1,2,:]
print(Ejer4c)

[56 57 58 59 60]


In [20]:
Ejer4d = Ejer3[2,0,:]
print(Ejer4d)

[91 92 93 94 95]


In [21]:
np.dot(Ejer4c, Ejer4d)

26980

In [25]:
Ejer4e = Ejer3[0,:,-1].reshape((1,-1))
print(Ejer4e)

[[ 5 10 15 20 25 30 35 40 45]]


In [26]:
Ejer4f = Ejer3[3,:,2].reshape((1,-1))
print(Ejer4f)

[[138 143 148 153 158 163 168 173 178]]


In [34]:
np.dot(Ejer4e.reshape(-1), Ejer4f.reshape(-1))

37050