In [2]:
import numpy as np

## Ejercicio 1

In [4]:
array1 = np.array([10, 12, 14, 16])
print(array1)

[10 12 14 16]


## Ejercicio 2

In [8]:
print(f"array1 contiene datos de tipo {array1.dtype}.")

array1 contiene datos de tipo int32.


## Ejercicio 3

In [10]:
print(f"El tamaño de array1 es {array1.shape}.")

El tamaño de array1 es (4,).


## Ejercicio 4

In [11]:
ceros = np.zeros((5,4))
unos = np.ones((5,4))
print(ceros)
print(unos)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Ejercicio 5

In [14]:
identidad = np.eye(7)
print(identidad)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


## Ejercicio 6

In [15]:
secuencia = np.arange(1,101)
print(secuencia)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


## Ejercicio 7

In [21]:
pares = np.arange(0, 18, 2)
print(pares)
pares = np.reshape(pares, (3,3))
print(pares)
pares = pares + np.eye(3)
print(pares)

[ 0  2  4  6  8 10 12 14 16]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 1.  2.  4.]
 [ 6.  9. 10.]
 [12. 14. 17.]]


## Ejercicio 8

In [22]:
inv = 1 / pares
print(inv)

[[1.         0.5        0.25      ]
 [0.16666667 0.11111111 0.1       ]
 [0.08333333 0.07142857 0.05882353]]


## Ejercicio 9

In [23]:
raiz = np.sqrt(inv)
print(raiz)

[[1.         0.70710678 0.5       ]
 [0.40824829 0.33333333 0.31622777]
 [0.28867513 0.26726124 0.24253563]]
