In [2]:
import numpy as np

## Ejercicio 1

In [3]:
fila = np.arange(20, 31)
print(fila)

[20 21 22 23 24 25 26 27 28 29 30]


## Ejercicio 2

In [4]:
fila_corto = fila[:6]
print(fila_corto)

[20 21 22 23 24 25]


## Ejercicio 3

In [6]:
Ejer3a = np.arange(100, 201)
print(Ejer3a)
Ejer3b = Ejer3a[:10].copy()
print(Ejer3b)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]
[100 101 102 103 104 105 106 107 108 109]


## Ejercicio 4

In [8]:
Ejer3b[::2] = 9999
print(Ejer3a)
print(Ejer3b)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]
[9999  101 9999  103 9999  105 9999  107 9999  109]


## Ejercicio 5

Hay que tener cuidado que no se indexan por separado, que es como se indexan las listas.

In [25]:
Ejer5a = np.reshape(np.arange(10, 1, -1), (3,3))
print(Ejer5a)
Ejer5b = Ejer5a[:2].copy()
print(Ejer5b)
Ejer5c = Ejer5a[:,:2].copy()
print(Ejer5c)
Ejer5d = Ejer5a[1:,:2].copy()
print(Ejer5d)

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]
[[10  9  8]
 [ 7  6  5]]
[[10  9]
 [ 7  6]
 [ 4  3]]
[[7 6]
 [4 3]]
